X tem Atributo=Valor:-X ehUm C, C tem Atributo=Valor.

acre tem regiao=norte.
alagoas tem regiao=nordeste.
amapa tem regiao=norte.
amazonas tem regiao=norte.
bahia tem regiao=nordeste.
ceara tem regiao=nordeste.
distritoFederal tem regiao=centroOeste.
espiritoSanto tem regiao=sudeste.
goias tem regiao=centroOeste.
maranhao tem regiao=nordeste.
matoGrosso tem regiao=centroOeste.
matoGrossoDoSul tem regiao=centroOeste.
minasGerais tem regiao=sudeste.
parana tem regiao=sul.
paraiba tem regiao=nordeste.
para tem regiao=norte.
pernambuco tem regiao=nordeste.
piaui tem regiao=nordeste.
rioDeJaneiro tem regiao=sudeste.
rioGrandeDoNorte tem regiao=nordeste.
rioGrandeDoSul tem regiao=sul.
rondonia tem regiao=norte.
roraima tem regiao=norte.
santaCatarina tem regiao=sul.
sergipe tem regiao=nordeste.
saoPaulo tem regiao=sudeste.
tocantins tem regiao=norte.

acre tem numeroHabitantes=795145.
alagoas tem numeroHabitantes=3327551.
amapa tem numeroHabitantes=756500.
amazonas tem numeroHabitantes=3893763.
bahia tem numeroHabitantes=15150143.
ceara tem numeroHabitantes=8867448.
distritoFederal tem numeroHabitantes=2867869.
espiritoSanto tem numeroHabitantes=3894899.
goias tem numeroHabitantes=6551322.
maranhao tem numeroHabitantes=6861924.
matoGrosso tem numeroHabitantes=3236578.
matoGrossoDoSul tem numeroHabitantes=2630098.
minasGerais tem numeroHabitantes=20777672.
parana tem numeroHabitantes=11112062.
paraiba tem numeroHabitantes=3950359.
para tem numeroHabitante=8101180.
pernambuco tem numeroHabitantes=9297861.
piaui tem numeroHabitantes=3198185.
rioDeJaneiro tem numeroHabitantes=16497395.
rioGrandeDoNorte tem numeroHabitantes=3419550.
rioGrandeDoSul tem numeroHabitantes=11228091.
rondonia tem numeroHabitantes=1755015.
roraima tem numeroHabitantes=500826.
santaCatarina tem numeroHabitantes=6734568.
saoPaulo tem numeroHabitantes=44169350.
sergipe tem numeroHabitantes=2227294.
tocantins tem numeroHabitantes=1502759.

acre tem acessoAoLitoral= false.  
alagoas tem acessoAoLitoral= true.
amapa tem acessoAoLitoral= true.
amazonas tem acessoAoLitoral= false.
bahia tem acessoAoLitoral= true.
ceara tem acessoAoLitoral= true.
distritoFederal tem acessoAoLitoral= false.
espiritoSanto tem acessoAoLitoral= true.
goias tem acessoAoLitoral= false.
maranhao tem acessoAoLitoral= true.
matoGrosso tem acessoAoLitoral= false.
matoGrossoDoSul tem acessoAoLitoral= false.
minasGerais tem acessoAoLitoral= false.
parana tem acessoAoLitoral= true.
paraiba tem acessoAoLitoral= true.
para tem acessoAoLitoral= true.
pernambuco tem acessoAoLitoral= true.
piaui tem acessoAoLitoral= true.
rioDeJaneiro tem acessoAoLitoral= true.
rioGrandeDoNorte tem acessoAoLitoral= true.
rioGrandeDoSul tem acessoAoLitoral= true.
rondonia tem acessoAoLitoral= false.
roraima tem acessoAoLitoral= false.
santaCatarina tem acessoAoLitoral= true.
sergipe tem acessoAoLitoral= true.
saoPaulo tem acessoAoLitoral= true.
tocantins tem acessoAoLitoral= false.

acre tem divisaOutraRegiao=false.
alagoas tem divisaOutraRegiao=false.
amapa tem divisaOutraRegiao=false.
amazonas tem divisaOutraRegiao=true.
bahia tem divisaOutraRegiao=true.
ceara tem divisaOutraRegiao=false.
distritoFederal tem divisaOutraRegiao=true.
espiritoSanto tem divisaOutraRegiao=true.
goias tem divisaOutraRegiao=true.
maranhao tem divisaOutraRegiao=true.
matoGrosso tem divisaOutraRegiao=true.
matoGrossoDoSul tem divisaOutraRegiao=true.
minasGerais tem divisaOutraRegiao=true.
parana tem divisaOutraRegiao=true.
paraiba tem divisaOutraRegiao=false.
para tem divisaOutraRegiao=true.
pernambuco tem divisaOutraRegiao=false.
piaui tem divisaOutraRegiao=true.
rioDeJaneiro tem divisaOutraRegiao=false.
rioGrandeDoNorte tem divisaOutraRegiao=false.
rioGrandeDoSul tem divisaOutraRegiao=false.
rondonia tem divisaOutraRegiao=true.
roraima tem divisaOutraRegiao=false.
santaCatarina tem divisaOutraRegiao=false.
sergipe tem divisaOutraRegiao=false.
saoPaulo tem divisaOutraRegiao=true.
tocantins tem divisaOutraRegiao=true.

acre tem densidadePopulacional=4.30.
alagoas tem densidadePopulacional=108.61.
amapa tem densidadePopulacional=4.16.
amazonas tem densidadePopulacional=2.05.
bahia tem densidadePopulacional=24.46.
ceara tem densidadePopulacional=54.40.
distritoFederal tem densidadePopulacional=400.73.
espiritoSanto tem densidadePopulacional=73.97.
goias tem densidadePopulacional=16.52.
maranhao tem densidadePopulacional=18.38.
matoGrosso tem densidadePopulacional=3.10.
matoGrossoDoSul tem densidadePopulacional=6.34.
minasGerais tem densidadePopulacional=32.79.
parana tem densidadePopulacional=51.48.
paraiba tem densidadePopulacional=63.71.
para tem densidadePopulacional=5.58.
pernambuco tem densidadePopulacional=85.58.
piaui tem densidadePopulacional=11.95.
rioDeJaneiro tem densidadePopulacional=352.05.
rioGrandeDoNorte tem densidadePopulacional=56.88.
rioGrandeDoSul tem densidadePopulacional=38.49.
rondonia tem densidadePopulacional=6.46.
roraima tem densidadePopulacional=1.74.
santaCatarina tem densidadePopulacional=61.53.
sergipe tem densidadePopulacional=89.81.
saoPaulo tem densidadePopulacional=162.93.
tocantins tem densidadePopulacional=4.70.

acre tem numeroDivisas=2.
alagoas tem numeroDivisas=3.
amapa tem numeroDivisas=1.
amazonas tem numeroDivisas=5.
bahia tem numeroDivisas=7.
ceara tem numeroDivisas=4.
distritoFederal tem numeroDivisas=2.
espiritoSanto tem numeroDivisas=3.
goias tem numeroDivisas=6.
maranhao tem numeroDivisas=3.
matoGrosso tem numeroDivisas=6.
matoGrossoDoSul tem numeroDivisas=5.
minasGerais tem numeroDivisas=6.
parana tem numeroDivisas=3.
paraiba tem numeroDivisas=3.
para tem numeroDivisas=6.
pernambuco tem numeroDivisas=5.
piaui tem numeroDivisas=5.
rioDeJaneiro tem numeroDivisas=3.
rioGrandeDoNorte tem numeroDivisas=2.
rioGrandeDoSul tem numeroDivisas=1.
rondonia tem numeroDivisas=3.
roraima tem numeroDivisas=2.
santaCatarina tem numeroDivisas=2.
sergipe tem numeroDivisas=2.
saoPaulo tem numeroDivisas=4.
tocantins tem numeroDivisas=6.

acre tem indiceAlfabetizacao=86.9.
alagoas tem indiceAlfabetizacao=80.6.
amapa tem indiceAlfabetizacao=95.
amazonas tem indiceAlfabetizacao=93.1.
bahia tem indiceAlfabetizacao=87.
ceara tem indiceAlfabetizacao=84.8.
distritoFederal tem indiceAlfabetizacao=97.4.
espiritoSanto tem indiceAlfabetizacao=93.8.
goias tem indiceAlfabetizacao=93.5.
maranhao tem indiceAlfabetizacao=83.3.
matoGrosso tem indiceAlfabetizacao=93.5.
matoGrossoDoSul tem indiceAlfabetizacao=93.7.
minasGerais tem indiceAlfabetizacao=93.8.
parana tem indiceAlfabetizacao=95.5.
paraiba tem indiceAlfabetizacao=83.7.
para tem indiceAlfabetizacao=90.7.
pernambuco tem indiceAlfabetizacao=87.2.
piaui tem indiceAlfabetizacao=82.8.
rioDeJaneiro tem indiceAlfabetizacao=97.3.
rioGrandeDoNorte tem indiceAlfabetizacao=85.3.
rioGrandeDoSul tem indiceAlfabetizacao=96.8.
rondonia tem indiceAlfabetizacao=93.3.
roraima tem indiceAlfabetizacao=93.4.
santaCatarina tem indiceAlfabetizacao=97.2.
sergipe tem indiceAlfabetizacao=85.3.
saoPaulo tem indiceAlfabetizacao=97.2.
tocantins tem indiceAlfabetizacao=89.6.

acre tem nome = 'Acre'. 
alagoas tem nome = 'Alagoas'.
amapa tem nome = 'Amapa'.
amazonas tem nome = 'Amazonas'.
bahia tem nome = 'Bahia'.
ceara tem nome = 'Ceara'.
distritoFederal tem nome = 'Distrito Federal'.
espiritoSanto tem nome = 'Espírito Santo'.
goias tem nome = 'Goiás'.
maranhao tem nome = 'Maranhão'.
matoGrosso tem nome = 'Mato Grosso'.
matoGrossoDoSul tem nome = 'Mato Grosso do Sul'.
minasGerais tem nome = 'Minas Gerais'.
parana tem nome = 'Paraná'.
paraiba tem nome = 'Paraíba'.
para tem nome = 'Pará'.
pernambuco tem nome = 'Pernambuco'.
piaui tem nome = 'Piauí'.
rioDeJaneiro tem nome = 'Rio de Janeiro'.
rioGrandeDoNorte tem nome = 'Rio Grande do Norte'.
rioGrandeDoSul tem nome = 'Rio Grande do Sul'.
rondonia tem nome = 'Rondônia'.
roraima tem nome = 'Roraima'.
santaCatarina tem nome = 'Santa Catarina'.
sergipe tem nome = 'Sergipe'.
saoPaulo tem nome = 'São Paulo'.
tocantins tem nome = 'Tocantins'.

'Distrito Federal' eh composto.
'Espírito Santo' eh composto.
'Mato Grosso' eh composto.
'Mato Grosso do Sul' eh composto.
'Minas Gerais' eh composto.
'Rio de Janeiro' eh composto.
'Rio Grande do Norte' eh composto.
'Rio Grande do Sul' eh composto.
'Santa Catarina' eh composto.
'São Paulo' eh composto.
