acre tem regiao=norte.
alagoas tem regiao=nordeste.
amapa tem regiao=norte.
amazonas tem regiao=norte.
bahia tem regiao=nordeste.
ceara tem regiao=nordeste.
distritoFederal tem regiao=centroOeste.
espiritoSanto tem regiao=sudeste.
goias tem regiao=centroOeste.
maranhao tem regiao=nordeste.
matoGrosso tem regiao=centroOeste.
matoGrossoDoSul tem regiao=centroOeste.
minasGerais tem regiao=sudeste.
parana tem regiao=sul.
paraiba tem regiao=nordeste.
para tem regiao=norte.
pernambuco tem regiao=nordeste.
piaui tem regiao=nordeste.
rioDeJaneiro tem regiao=sudeste.
rioGrandeDoNorte tem regiao=nordeste.
rioGrandeDoSul tem regiao=sul.
rondonia tem regiao=norte.
roraima tem regiao=norte.
santaCatarina tem regiao=sul.
sergipe tem regiao=nordeste.
saoPaulo tem regiao=sudeste.
tocantins tem regiao=norte.

acre tem numeroHabitantes=795145.
alagoas tem numeroHabitantes=3327551.
amapa tem numeroHabitantes=756500.
amazonas tem numeroHabitantes=3893763.
bahia tem numeroHabitantes=15150143.
ceara tem numeroHabitantes=8867448.
distritoFederal tem numeroHabitantes=2867869.
espiritoSanto tem numeroHabitantes=3894899.
goias tem numeroHabitantes=6551322.
maranhao tem numeroHabitantes=6861924.
matoGrosso tem numeroHabitantes=3236578.
matoGrossoDoSul tem numeroHabitantes=2630098.
minasGerais tem numeroHabitantes=20777672.
parana tem numeroHabitantes=11112062.
paraiba tem numeroHabitantes=3950359.
para tem numeroHabitante=8101180.
pernambuco tem numeroHabitantes=9297861.
piaui tem numeroHabitantes=3198185.
rioDeJaneiro tem numeroHabitantes=16497395.
rioGrandeDoNorte tem numeroHabitantes=3419550.
rioGrandeDoSul tem numeroHabitantes=11228091.
rondonia tem numeroHabitantes=1755015.
roraima tem numeroHabitantes=500826.
santaCatarina tem numeroHabitantes=6734568.
saoPaulo tem numeroHabitantes=44169350.
sergipe tem numeroHabitantes=2227294.
tocantins tem numeroHabitantes=1502759.

acre tem acessoAoLitoral= false.  
alagoas tem acessoAoLitoral= true.
amapa tem acessoAoLitoral= true.
amazonas tem acessoAoLitoral= false.
bahia tem acessoAoLitoral= true.
ceara tem acessoAoLitoral= true.
distritoFederal tem acessoAoLitoral= false.
espiritoSanto tem acessoAoLitoral= true.
goias tem acessoAoLitoral= false.
maranhao tem acessoAoLitoral= true.
matoGrosso tem acessoAoLitoral= false.
matoGrossoDoSul tem acessoAoLitoral= false.
minasGerais tem acessoAoLitoral= false.
parana tem acessoAoLitoral= true.
paraiba tem acessoAoLitoral= true.
para tem acessoAoLitoral= true.
pernambuco tem acessoAoLitoral= true.
piaui tem acessoAoLitoral= true.
rioDeJaneiro tem acessoAoLitoral= true.
rioGrandeDoNorte tem acessoAoLitoral= true.
rioGrandeDoSul tem acessoAoLitoral= true.
rondonia tem acessoAoLitoral= false.
roraima tem acessoAoLitoral= false.
santaCatarina tem acessoAoLitoral= true.
sergipe tem acessoAoLitoral= true.
saoPaulo tem acessoAoLitoral= true.
tocantins tem acessoAoLitoral= false.
